// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for About Page Text documents */
interface AboutPageTextDocumentData {
    /**
     * Slice Zone field in *About Page Text*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: about_page_text.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<AboutPageTextDocumentDataSlicesSlice>;
}
/**
 * Slice for *About Page Text → Slice Zone*
 *
 */
type AboutPageTextDocumentDataSlicesSlice = AboutTextSlice;
/**
 * About Page Text document from Prismic
 *
 * - **API ID**: `about_page_text`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutPageTextDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<AboutPageTextDocumentData>, "about_page_text", Lang>;
export type AllDocumentTypes = AboutPageTextDocument;
/**
 * Primary content in AboutText → Primary
 *
 */
interface AboutTextSliceDefaultPrimary {
    /**
     * Title field in *AboutText → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: about_text.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Description field in *AboutText → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: about_text.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * aboutHero_belowSquareL field in *AboutText → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: about_text.primary.abouthero_belowsquareL
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    abouthero_belowsquareL: prismicT.ImageField<never>;
}
/**
 * Default variation for AboutText Slice
 *
 * - **API ID**: `default`
 * - **Description**: `AboutText`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type AboutTextSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<AboutTextSliceDefaultPrimary>, never>;
/**
 * Slice variation for *AboutText*
 *
 */
type AboutTextSliceVariation = AboutTextSliceDefault;
/**
 * AboutText Shared Slice
 *
 * - **API ID**: `about_text`
 * - **Description**: `AboutText`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type AboutTextSlice = prismicT.SharedSlice<"about_text", AboutTextSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { AboutPageTextDocumentData, AboutPageTextDocumentDataSlicesSlice, AboutPageTextDocument, AllDocumentTypes, AboutTextSliceDefaultPrimary, AboutTextSliceDefault, AboutTextSliceVariation, AboutTextSlice };
    }
}
