// Code generated by Slice Machine. DO NOT EDIT.

import AboutImages from './AboutImages';
import AboutText from './AboutText';

export {
	AboutImages,
	AboutText,
};

export const components = {
	about_images: AboutImages,
	about_text: AboutText,
};
