// Code generated by Slice Machine. DO NOT EDIT.

import AboutImages from './AboutImages';
import AboutText from './AboutText';
import HomeBottomCards from './HomeBottomCards';
import Logos from './Logos';

export {
	AboutImages,
	AboutText,
	HomeBottomCards,
	Logos,
};

export const components = {
	about_images: AboutImages,
	about_text: AboutText,
	home_bottom_cards: HomeBottomCards,
	logos: Logos,
};
